name: Keep Alive

on:
  schedule:
    - cron: "*/20 * * * *"  # every 20 minutes


jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping health endpoint
        run: curl https://johntemitope.tech/health